/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alimundo.moduloalmacen;

import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author AdminSrv
 */
public class EntradaMaterial extends javax.swing.JDialog {

    Conexion con = new Conexion();
    ValidarDatos validar = new ValidarDatos();
    String error;
    int errorsql;

    public EntradaMaterial() {
        initComponents();
        setSize(509, 471);
        setResizable(false);
        setLocationRelativeTo(null);
        new CargarComponentes().llenarchoice(choicecategorias, "EXEC spu_retornacategorias");
        new CargarComponentes().llenarchoice(choicemedidas, "EXEC spu_retornamedidas");
        new CargarComponentes().llenarchoice(choicealmacenes, "EXEC spu_retornaalmacenes");
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeltitulo = new javax.swing.JLabel();
        labeltitulo1 = new javax.swing.JLabel();
        labelcerrar = new javax.swing.JLabel();
        labelcodigo = new javax.swing.JLabel();
        textfieldcodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        labelnommat = new javax.swing.JLabel();
        texfieldnombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        labelcategoria = new javax.swing.JLabel();
        choicecategorias = new java.awt.Choice();
        labelmedida = new javax.swing.JLabel();
        choicemedidas = new java.awt.Choice();
        labelalmacen = new javax.swing.JLabel();
        choicealmacenes = new java.awt.Choice();
        labelcantidad = new javax.swing.JLabel();
        botonmas = new javax.swing.JButton();
        botonmenos = new javax.swing.JButton();
        textfieldcantidad = new javax.swing.JTextField();
        labeldescripcion = new javax.swing.JLabel();
        textfielddescripcion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        botonaceptar = new javax.swing.JButton();
        botonbuscar = new javax.swing.JButton();
        labelbuscar = new javax.swing.JLabel();
        labelaceptar = new javax.swing.JLabel();
        botonmodificar = new javax.swing.JButton();
        labelmodificar = new javax.swing.JLabel();
        panelopciones = new javax.swing.JPanel();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        getContentPane().setLayout(null);

        labeltitulo.setBackground(new java.awt.Color(255, 255, 255));
        labeltitulo.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labeltitulo.setText("DE MATERIAL ");
        labeltitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(labeltitulo);
        labeltitulo.setBounds(170, 30, 170, 30);

        labeltitulo1.setBackground(new java.awt.Color(255, 255, 255));
        labeltitulo1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labeltitulo1.setText("ENTRADA Y MODIFICACIÓN");
        labeltitulo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(labeltitulo1);
        labeltitulo1.setBounds(90, 10, 320, 28);

        labelcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngs32X32/cancel.png"))); // NOI18N
        labelcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcerrarMouseClicked(evt);
            }
        });
        getContentPane().add(labelcerrar);
        labelcerrar.setBounds(470, 0, 32, 40);

        labelcodigo.setBackground(new java.awt.Color(0, 153, 204));
        labelcodigo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcodigo.setText("Codigo:");
        labelcodigo.setOpaque(true);
        getContentPane().add(labelcodigo);
        labelcodigo.setBounds(70, 80, 90, 30);

        textfieldcodigo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textfieldcodigo.setForeground(new java.awt.Color(255, 0, 0));
        textfieldcodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textfieldcodigo.setOpaque(false);
        getContentPane().add(textfieldcodigo);
        textfieldcodigo.setBounds(170, 80, 300, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(170, 110, 300, 10);

        labelnommat.setBackground(new java.awt.Color(0, 153, 204));
        labelnommat.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelnommat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnommat.setText("Nombre:");
        labelnommat.setOpaque(true);
        getContentPane().add(labelnommat);
        labelnommat.setBounds(70, 120, 90, 30);

        texfieldnombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        texfieldnombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        texfieldnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        texfieldnombre.setOpaque(false);
        getContentPane().add(texfieldnombre);
        texfieldnombre.setBounds(170, 120, 300, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(170, 150, 300, 10);

        labelcategoria.setBackground(new java.awt.Color(0, 153, 204));
        labelcategoria.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelcategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcategoria.setText("Categoria:");
        labelcategoria.setOpaque(true);
        getContentPane().add(labelcategoria);
        labelcategoria.setBounds(70, 160, 90, 30);

        choicecategorias.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(choicecategorias);
        choicecategorias.setBounds(170, 160, 280, 40);

        labelmedida.setBackground(new java.awt.Color(0, 153, 204));
        labelmedida.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelmedida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelmedida.setText("Medida:");
        labelmedida.setOpaque(true);
        getContentPane().add(labelmedida);
        labelmedida.setBounds(90, 200, 70, 30);
        getContentPane().add(choicemedidas);
        choicemedidas.setBounds(170, 200, 280, 40);

        labelalmacen.setBackground(new java.awt.Color(0, 153, 204));
        labelalmacen.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelalmacen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelalmacen.setText("Asignar Almacén:");
        labelalmacen.setOpaque(true);
        getContentPane().add(labelalmacen);
        labelalmacen.setBounds(10, 240, 150, 30);
        getContentPane().add(choicealmacenes);
        choicealmacenes.setBounds(170, 240, 280, 40);

        labelcantidad.setBackground(new java.awt.Color(0, 153, 204));
        labelcantidad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelcantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcantidad.setText("Cantidad:");
        labelcantidad.setOpaque(true);
        getContentPane().add(labelcantidad);
        labelcantidad.setBounds(80, 280, 80, 30);

        botonmas.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        botonmas.setText("+");
        botonmas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonmas.setOpaque(false);
        botonmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonmasMouseClicked(evt);
            }
        });
        getContentPane().add(botonmas);
        botonmas.setBounds(250, 276, 30, 40);

        botonmenos.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        botonmenos.setText("-");
        botonmenos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonmenos.setOpaque(false);
        botonmenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonmenosMouseClicked(evt);
            }
        });
        getContentPane().add(botonmenos);
        botonmenos.setBounds(280, 276, 30, 40);

        textfieldcantidad.setEditable(false);
        textfieldcantidad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textfieldcantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfieldcantidad.setText("0");
        textfieldcantidad.setToolTipText("");
        getContentPane().add(textfieldcantidad);
        textfieldcantidad.setBounds(170, 280, 80, 30);

        labeldescripcion.setBackground(new java.awt.Color(0, 153, 204));
        labeldescripcion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labeldescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeldescripcion.setText("Descripción:");
        labeldescripcion.setOpaque(true);
        getContentPane().add(labeldescripcion);
        labeldescripcion.setBounds(50, 320, 110, 30);

        textfielddescripcion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        textfielddescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textfielddescripcion.setOpaque(false);
        getContentPane().add(textfielddescripcion);
        textfielddescripcion.setBounds(170, 320, 300, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(170, 350, 300, 10);

        botonaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngs64X64/verificar.png"))); // NOI18N
        botonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonaceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonaceptar);
        botonaceptar.setBounds(390, 360, 80, 80);

        botonbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngs64X64/buscar.png"))); // NOI18N
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonbuscar);
        botonbuscar.setBounds(310, 360, 80, 80);

        labelbuscar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelbuscar.setText("Buscar");
        getContentPane().add(labelbuscar);
        labelbuscar.setBounds(324, 440, 50, 16);

        labelaceptar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelaceptar.setText("Aceptar");
        getContentPane().add(labelaceptar);
        labelaceptar.setBounds(402, 440, 60, 16);

        botonmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngs64X64/edit.png"))); // NOI18N
        botonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(botonmodificar);
        botonmodificar.setBounds(230, 360, 80, 80);

        labelmodificar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelmodificar.setText("Modificar");
        getContentPane().add(labelmodificar);
        labelmodificar.setBounds(240, 440, 70, 16);

        panelopciones.setBackground(new java.awt.Color(0, 102, 153));
        panelopciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelopciones);
        panelopciones.setBounds(0, 0, 30, 470);

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        labelfondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(labelfondo);
        labelfondo.setBounds(0, 0, 510, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void botonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonaceptarActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        PreparedStatement ps = null;
        ResultSet rs = null;
        Object[] textoOpciones = {"Si", "No"};
        int opc = JOptionPane.showOptionDialog(null, "<html><h3 style=font-family:Verdana New;>¿Esta Seguro que Desea Guardar la Entrada?</h3></html>",
                null, JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, new Parametros().iconpregunta, textoOpciones, textoOpciones[0]);
        if (opc == 0) {
            if (validar.vacio(this.textfieldcodigo.getText(), this.texfieldnombre.getText())) {
                if (validar.ValidaCantidad(Integer.parseInt(this.textfieldcantidad.getText()))) {
                    try {
                        ps = con.EstablecerConexion().prepareStatement("EXEC spu_guardanvomaterial ?,?,?,?,?,?,?");
                        ps.setString(1, this.textfieldcodigo.getText());
                        ps.setString(2, this.texfieldnombre.getText());
                        ps.setString(3, this.choicecategorias.getSelectedItem());
                        ps.setString(4, this.choicemedidas.getSelectedItem());
                        ps.setString(5, this.choicealmacenes.getSelectedItem());
                        ps.setInt(6, Integer.parseInt(this.textfieldcantidad.getText()));
                        ps.setString(7, this.textfielddescripcion.getText());
                        rs = ps.executeQuery();
                        while (rs.next()) {
                            JOptionPane.showMessageDialog(null, "<html><h3 style=font-family:Verdana;>Material Guardado con Exito </h3></html>",
                                    null, JOptionPane.PLAIN_MESSAGE, new Parametros().iconinformacion);
                            this.textfieldcodigo.setText(" ");
                            this.texfieldnombre.setText(" ");
                            this.textfieldcantidad.setText("0");
                            this.textfielddescripcion.setText(" ");
                        }
                        ps.close();
                    } catch (SQLException ex) {
                        errorsql = ex.getErrorCode();
                        if (errorsql == 2627) {
                            JOptionPane.showMessageDialog(null, "<html><h3 style=font-family:Verdana;>El Material ya existe en el Sistema</h3></html>",
                                    "ERROR", JOptionPane.PLAIN_MESSAGE, new Parametros().iconerror);
                        } else {
                            error = ex.getMessage();
                            JOptionPane.showMessageDialog(null, error, "ERROR", JOptionPane.PLAIN_MESSAGE, new Parametros().iconerror);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "<html><h3 style=font-family:Verdana;>La cantidad debe ser mayor a 0</h3></html>",
                            "ERROR", JOptionPane.PLAIN_MESSAGE, new Parametros().iconerror);
                }
            } else {
                JOptionPane.showMessageDialog(null, "<html><h3 style=font-family:Verdana;>El Codigo y Nombre no pueden estar vacios</h3></html>",
                        "ERROR", JOptionPane.PLAIN_MESSAGE, new Parametros().iconerror);
            }
        }
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonaceptarActionPerformed

    private void labelcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarMouseClicked
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        this.dispose();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_labelcerrarMouseClicked

    private void botonmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonmasMouseClicked
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        int acumulador;
        acumulador = Integer.parseInt(this.textfieldcantidad.getText());
        acumulador = acumulador + 1;
        this.textfieldcantidad.setText(String.valueOf(acumulador));
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_botonmasMouseClicked

    private void botonmenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonmenosMouseClicked
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        int acumulador;
        acumulador = Integer.parseInt(this.textfieldcantidad.getText());
        if (acumulador == 0) {
            acumulador = 0;
        } else {
            acumulador = acumulador - 1;
        }
        this.textfieldcantidad.setText(String.valueOf(acumulador));
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonmenosMouseClicked

    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        this.dispose();
        new Busqueda().setVisible(true);
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonbuscarActionPerformed

    private void botonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmodificarActionPerformed
        if(validar.vacio(this.textfieldcodigo.getText(),this.texfieldnombre.getText())){
            try {
                PreparedStatement ps = null;
                ResultSet rs = null;
                ps = con.EstablecerConexion().prepareStatement("EXEC spu_modificarmaterial ?,?,?,?,?,?");
                ps.setString(1, this.textfieldcodigo.getText());
                ps.setString(2, this.texfieldnombre.getText());
                ps.setString(3, this.choicecategorias.getSelectedItem());
                ps.setString(4, this.choicemedidas.getSelectedItem());
                ps.setString(5, this.choicealmacenes.getSelectedItem());
                ps.setString(6, this.textfielddescripcion.getText());
                rs = ps.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "<html><h3 style=font-family:Verdana;>Material Modificado con Exito </h3></html>",
                            null, JOptionPane.PLAIN_MESSAGE, new Parametros().iconinformacion);
                    this.textfieldcodigo.setText(" ");
                    this.texfieldnombre.setText(" ");
                    this.textfieldcantidad.setText("0");
                    this.textfielddescripcion.setText(" ");
                }
                ps.close();
            } catch (SQLException ex) {
                errorsql = ex.getErrorCode();
                if (errorsql == 0){
                    JOptionPane.showMessageDialog(null, "<html><h3 style=font-family:Verdana;>El Codigo ingresado no existe en el Sistema</h3></html>",
                                    "ERROR", JOptionPane.PLAIN_MESSAGE, new Parametros().iconerror);
                }else{
                    JOptionPane.showMessageDialog(null, error, "ERROR", JOptionPane.PLAIN_MESSAGE, new Parametros().iconerror);
                }
            }
        }else {JOptionPane.showMessageDialog(null, "<html><h3 style=font-family:Verdana;>El Codigo y Nombre no pueden estar vacios</h3></html>",
                        "ERROR", JOptionPane.PLAIN_MESSAGE, new Parametros().iconerror);
            
        }
    }//GEN-LAST:event_botonmodificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonaceptar;
    private javax.swing.JButton botonbuscar;
    public javax.swing.JButton botonmas;
    public javax.swing.JButton botonmenos;
    private javax.swing.JButton botonmodificar;
    public java.awt.Choice choicealmacenes;
    public java.awt.Choice choicecategorias;
    public java.awt.Choice choicemedidas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelaceptar;
    private javax.swing.JLabel labelalmacen;
    private javax.swing.JLabel labelbuscar;
    private javax.swing.JLabel labelcantidad;
    private javax.swing.JLabel labelcategoria;
    private javax.swing.JLabel labelcerrar;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labeldescripcion;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labelmedida;
    private javax.swing.JLabel labelmodificar;
    private javax.swing.JLabel labelnommat;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JLabel labeltitulo1;
    private javax.swing.JPanel panelopciones;
    public javax.swing.JTextField texfieldnombre;
    public javax.swing.JTextField textfieldcantidad;
    public javax.swing.JTextField textfieldcodigo;
    public javax.swing.JTextField textfielddescripcion;
    // End of variables declaration//GEN-END:variables

}
