/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import com.alimundo.moduloalmacen.Conexion;
import com.alimundo.moduloalmacen.Parametros;
import com.alimundo.moduloalmacen.RequisicionesSalidas;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author AdminSrv
 */
public class Salidas extends javax.swing.JPanel {

    TableColumnModel columnModel;
    public static DefaultTableModel modelodptofecha = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int filas, int columnas){
            if (columnas <= 2){
                return false;
            }else return true;
        }
    };
    public static DefaultTableModel modelosalida = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int filas, int columnas){
            if (columnas <= 5){
                return false;
            }else return true;
        } 
    };
    public void tamanocolumnassalidas(JTable table){
        columnModel = table.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(250);
        columnModel.getColumn(1).setPreferredWidth(900);
        columnModel.getColumn(2).setPreferredWidth(500);
        columnModel.getColumn(3).setPreferredWidth(400);
        columnModel.getColumn(4).setPreferredWidth(400);
        columnModel.getColumn(5).setPreferredWidth(200);
        columnModel.getColumn(6).setPreferredWidth(900);
    } 
    public final void tamanocolumnasdptofecha(JTable table){
        columnModel = table.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(900);
        columnModel.getColumn(1).setPreferredWidth(600);
    }
    
    Conexion con = new Conexion();
    String error;
    Date fechahoy;
    String fechaformat = "dd/MM/yyyy";
    JTextFieldDateEditor editor;
    
    public Salidas() {
        
        initComponents();
         modelosalida.setColumnIdentifiers(new Object[]{"<html><h3 style=font-family:Verdana;>Codigo</h3></html>","<html><h3 style=font-family:Verdana;>Nombre Material</h3></html>",
            "<html><h3 style=font-family:Verdana;>Categoria</h3></html>","<html><h3 style=font-family:Verdana;>Medida</h3></html>","<html><h3 style=font-family:Verdana;>Almacén</h3></html>",
            "<html><h3 style=font-family:Verdana;>Cant.</h3></html>","<html><h3 style=font-family:Verdana;>Descripción / Uso</h3></html>"});
        tamanocolumnassalidas(tablesalidas); 
        modelosalida.setRowCount(0);
        tablesalidas.getTableHeader().setResizingAllowed(false);
        tablesalidas.getTableHeader().setReorderingAllowed(false);
        
        modelodptofecha.setColumnIdentifiers(new Object[]{"<html><h3 style=font-family:Verdana;>Entrega Departamento</h3></html>",
                                                "<html><h3 style=font-family:Verdana;>Fecha Requisición</h3></html>"});
        this.tamanocolumnasdptofecha(tabledptofecha);
                modelodptofecha.setRowCount(0);
        tabledptofecha.getTableHeader().setReorderingAllowed(false);
        tabledptofecha.getTableHeader().setResizingAllowed(false);
        ((DefaultTableCellRenderer) tabledptofecha.getTableHeader().getDefaultRenderer())
                       .setHorizontalAlignment(SwingConstants.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeltitulo = new javax.swing.JLabel();
        labelnid = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        botoncargareq = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tablesalidas = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledptofecha = new javax.swing.JTable();
        labelfondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1189, 419));
        setMinimumSize(new java.awt.Dimension(1189, 419));
        setPreferredSize(new java.awt.Dimension(1189, 419));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltitulo.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labeltitulo.setText("SALIDAS DEL ALMACÉN");
        labeltitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(labeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 280, -1));

        labelnid.setBackground(new java.awt.Color(255, 255, 255));
        labelnid.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelnid.setForeground(new java.awt.Color(255, 0, 0));
        labelnid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnid.setEnabled(false);
        labelnid.setFocusable(false);
        labelnid.setOpaque(true);
        add(labelnid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 44, 50, 40));

        labelid.setBackground(new java.awt.Color(255, 255, 255));
        labelid.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelid.setText("ID Salida");
        labelid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(labelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, -1, -1));

        botoncargareq.setBackground(new java.awt.Color(0, 0, 0));
        botoncargareq.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        botoncargareq.setForeground(new java.awt.Color(255, 255, 255));
        botoncargareq.setText("Cargar Requisición");
        botoncargareq.setBorder(null);
        botoncargareq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncargareqActionPerformed(evt);
            }
        });
        add(botoncargareq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 40));

        tablesalidas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tablesalidas.setModel(modelosalida);
        tablesalidas.setShowGrid(true);
        tablesalidas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablesalidasKeyPressed(evt);
            }
        });
        jScrollPane.setViewportView(tablesalidas);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1170, 290));

        tabledptofecha.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tabledptofecha.setModel(modelodptofecha);
        jScrollPane1.setViewportView(tabledptofecha);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 400, 70));

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -6, 1210, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void tablesalidasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablesalidasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if (tablesalidas.getSelectedRowCount() > 0) {
                modelosalida.removeRow(tablesalidas.getSelectedRow());
            }
            else{
                JOptionPane.showMessageDialog(null,"<html><h3 style=font-family:Verdana;>Debe Seleccionar un Registro</h3></html>",null,JOptionPane.PLAIN_MESSAGE,new Parametros().iconadvertencia);
            }
        }
    }//GEN-LAST:event_tablesalidasKeyPressed

    private void botoncargareqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncargareqActionPerformed
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        new RequisicionesSalidas().setVisible(true);
        tamanocolumnassalidas(tablesalidas);
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botoncargareqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncargareq;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labelid;
    public javax.swing.JLabel labelnid;
    private javax.swing.JLabel labeltitulo;
    public javax.swing.JTable tabledptofecha;
    public javax.swing.JTable tablesalidas;
    // End of variables declaration//GEN-END:variables
}
